package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaUploadFile<M extends BaseOaUploadFile<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setCreateUserId(java.lang.String createUserId) {
		set("create_user_id", createUserId);
	}
	
	public java.lang.String getCreateUserId() {
		return getStr("create_user_id");
	}

	public void setCreateUserName(java.lang.String createUserName) {
		set("create_user_name", createUserName);
	}
	
	public java.lang.String getCreateUserName() {
		return getStr("create_user_name");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

	public void setUpdateUserId(java.lang.String updateUserId) {
		set("update_user_id", updateUserId);
	}
	
	public java.lang.String getUpdateUserId() {
		return getStr("update_user_id");
	}

	public void setUpdateUserName(java.lang.String updateUserName) {
		set("update_user_name", updateUserName);
	}
	
	public java.lang.String getUpdateUserName() {
		return getStr("update_user_name");
	}

	public void setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
	}
	
	public java.lang.String getUpdateTime() {
		return getStr("update_time");
	}

	public void setFileName(java.lang.String fileName) {
		set("file_name", fileName);
	}
	
	public java.lang.String getFileName() {
		return getStr("file_name");
	}

	public void setFileSuffix(java.lang.String fileSuffix) {
		set("file_suffix", fileSuffix);
	}
	
	public java.lang.String getFileSuffix() {
		return getStr("file_suffix");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public void setRealUrl(java.lang.String realUrl) {
		set("real_url", realUrl);
	}
	
	public java.lang.String getRealUrl() {
		return getStr("real_url");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
