package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaClient<M extends BaseOaClient<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCustId(java.lang.String custId) {
		set("cust_id", custId);
	}
	
	public java.lang.String getCustId() {
		return getStr("cust_id");
	}

	public void setCustName(java.lang.String custName) {
		set("cust_name", custName);
	}
	
	public java.lang.String getCustName() {
		return getStr("cust_name");
	}

	public void setCustEmail(java.lang.String custEmail) {
		set("cust_email", custEmail);
	}
	
	public java.lang.String getCustEmail() {
		return getStr("cust_email");
	}

	public void setCustPhone(java.lang.String custPhone) {
		set("cust_phone", custPhone);
	}
	
	public java.lang.String getCustPhone() {
		return getStr("cust_phone");
	}

	public void setCustGender(java.lang.String custGender) {
		set("cust_gender", custGender);
	}
	
	public java.lang.String getCustGender() {
		return getStr("cust_gender");
	}

	public void setCustAge(java.lang.Integer custAge) {
		set("cust_age", custAge);
	}
	
	public java.lang.Integer getCustAge() {
		return getInt("cust_age");
	}

	public void setCustProvince(java.lang.String custProvince) {
		set("cust_province", custProvince);
	}
	
	public java.lang.String getCustProvince() {
		return getStr("cust_province");
	}

	public void setCustDistricts(java.lang.String custDistricts) {
		set("cust_districts", custDistricts);
	}
	
	public java.lang.String getCustDistricts() {
		return getStr("cust_districts");
	}

	public void setCustCity(java.lang.String custCity) {
		set("cust_city", custCity);
	}
	
	public java.lang.String getCustCity() {
		return getStr("cust_city");
	}

	public void setCustCompanyCode(java.lang.String custCompanyCode) {
		set("cust_company_code", custCompanyCode);
	}
	
	public java.lang.String getCustCompanyCode() {
		return getStr("cust_company_code");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCustTenantId(java.lang.String custTenantId) {
		set("cust_tenant_id", custTenantId);
	}
	
	public java.lang.String getCustTenantId() {
		return getStr("cust_tenant_id");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
