package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActEvtLog<M extends BaseActEvtLog<M>> extends Model<M> implements IBean {

	public void setLogNr(java.lang.Long logNr) {
		set("LOG_NR_", logNr);
	}
	
	public java.lang.Long getLogNr() {
		return getLong("LOG_NR_");
	}

	public void setType(java.lang.String type) {
		set("TYPE_", type);
	}
	
	public java.lang.String getType() {
		return getStr("TYPE_");
	}

	public void setProcDefId(java.lang.String procDefId) {
		set("PROC_DEF_ID_", procDefId);
	}
	
	public java.lang.String getProcDefId() {
		return getStr("PROC_DEF_ID_");
	}

	public void setProcInstId(java.lang.String procInstId) {
		set("PROC_INST_ID_", procInstId);
	}
	
	public java.lang.String getProcInstId() {
		return getStr("PROC_INST_ID_");
	}

	public void setExecutionId(java.lang.String executionId) {
		set("EXECUTION_ID_", executionId);
	}
	
	public java.lang.String getExecutionId() {
		return getStr("EXECUTION_ID_");
	}

	public void setTaskId(java.lang.String taskId) {
		set("TASK_ID_", taskId);
	}
	
	public java.lang.String getTaskId() {
		return getStr("TASK_ID_");
	}

	public void setTimeStamp(java.util.Date timeStamp) {
		set("TIME_STAMP_", timeStamp);
	}
	
	public java.util.Date getTimeStamp() {
		return get("TIME_STAMP_");
	}

	public void setUserId(java.lang.String userId) {
		set("USER_ID_", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("USER_ID_");
	}

	public void setData(byte[] data) {
		set("DATA_", data);
	}
	
	public byte[] getData() {
		return get("DATA_");
	}

	public void setLockOwner(java.lang.String lockOwner) {
		set("LOCK_OWNER_", lockOwner);
	}
	
	public java.lang.String getLockOwner() {
		return getStr("LOCK_OWNER_");
	}

	public void setLockTime(java.util.Date lockTime) {
		set("LOCK_TIME_", lockTime);
	}
	
	public java.util.Date getLockTime() {
		return get("LOCK_TIME_");
	}

	public void setIsProcessed(java.lang.Integer isProcessed) {
		set("IS_PROCESSED_", isProcessed);
	}
	
	public java.lang.Integer getIsProcessed() {
		return getInt("IS_PROCESSED_");
	}

}
