package com.pointlion.sys.mvc.common.model;

import com.pointlion.sys.mvc.common.model.base.BaseOaClient;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaClient extends BaseOaClient<OaClient> {
	public static final OaClient dao = new OaClient().dao();
}
