package com.pointlion.sys.mvc.common.model;

import com.pointlion.sys.mvc.common.model.base.BaseOaLeave;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaLeave extends BaseOaLeave<OaLeave> {
	public static final OaLeave dao = new OaLeave().dao();
	public static final String tableName = "oa_leave";


	public OaLeave getById(String id) {
		return OaLeave.dao.findById(id);
	}
}
