package com.pointlion.sys.mvc.common.model;

import com.jfinal.aop.Before;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.jfinal.plugin.activerecord.tx.Tx;
import com.pointlion.sys.mvc.common.model.base.BaseOaUploadFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaUploadFile extends BaseOaUploadFile<OaUploadFile> {
	public static final OaUploadFile dao = new OaUploadFile().dao();
	public static final String tableName = "oa_upload_file";

	// 保存
	public int insert(OaUploadFile oaUploadFile){
		return 1;
	}

	/***
	 * 根据主键查询
	 */
	public OaUploadFile getById(String id){
		return OaUploadFile.dao.findById(id);
	}

	/***
	 * 获取分页
	 */
	public Page<Record> getPage(int pnum, int psize){
		String sql  = " from #(tableMeta.name) o ";
		return Db.paginate(pnum, psize, " select * ", sql);
	}

	/***
	 * 删除
	 * @param ids
	 */
	@Before(Tx.class)
	public void deleteByIds(String ids){
		String idarr[] = ids.split(",");
		for(String id : idarr){
			OaUploadFile o = OaUploadFile.dao.getById(id);
			o.delete();
		}
	}
}
